Cafe_feeling_happy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Cafe_feeling_happy.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("dish/", include("dish.urls", namespace="dish")),
    path("order/", include("order.urls", namespace="order")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dish/urls.py
from django.urls import path

from dish.views import (dish_type_view,
                        add_dish_to_users_order_view,
                        DishDetailView,
                        DishCreateView,
                        DishDeleteView,
                        DishUpdateView)

urlpatterns = [
    path("details/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("details/<int:pk>/add_to_order/", add_dish_to_users_order_view, name="add-to-order"),
    path("create/", DishCreateView.as_view(), name="dish-create"),
    path("<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("<str:dish_type>/", dish_type_view, name="dish-list"),
]

app_name = "dish"

order/urls.py
from django.urls import path

from order.views import (add_dish_to_users_order_view,
                         remove_dish_from_users_order_view,
                         OrderListView,
                         OrderDetailView,
                         OrderConfirmByUserView)

urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order-list"),
    path("order_detail/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("order_detail/<int:pk>/add_dish/", add_dish_to_users_order_view, name="order-detail-add"),
    path("<int:pk>/remove_dish/", remove_dish_from_users_order_view, name="order-detail-remove"),
    path("order_detail/<int:pk>/confirm_by_user/", OrderConfirmByUserView.as_view(), name="confirm-order-by-user"),
]

app_name = "order"

user/urls.py
from django.urls import path

from user.views import CreateUserView, UserDetailView, UserUpdateView

urlpatterns = [
    path("registration/", CreateUserView.as_view(), name="registration"),
    path("user_detail/", UserDetailView.as_view(), name="user-detail"),
    path("user_update/<int:pk>", UserUpdateView.as_view(), name="user-update")

]

app_name = "user"

templates/includes/footer.html
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Feeling Happy</h3>
              <p>
                Stritenska, 22A St. <br>
                Poltava, Ukraine<br><br>
                <strong>Phone:</strong> +380 (99) 468 17 22<br>
              </p>
              <div class="social-links mt-3">
                <a href="https://www.instagram.com/feeling_happy_pl/" class="instagram"><i class="bx bxl-twitter"><img src="/static/assets/img/socials/instagram.png" alt="instagram" style="height: 20px; width: auto;"></i></a>
                <a href="https://www.facebook.com/feeling.happy.poltava/" class="facebook"><i class="bx bxl-facebook"><img src="/static/assets/img/socials/facebook.png" alt="facebook" style="height: 20px; width: auto;"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'index' %}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="https://feeling-happy.business.site/">About us</a></li>
              <li><i class="bx bx-chevron-right"></i>
                <a href="https://www.google.com/maps/place/%D0%9A%D0%B0%D1%84%D0%B5+Feeling+Happy/@49.5864663,34.5575864,17z/data=!3m1!4b1!4m6!3m5!1s0x40d8255c435aea07:0xc6aa9a9d68ec69db!8m2!3d49.5864663!4d34.5601613!16s%2Fg%2F11j35ktr1h?entry=ttu">
                  How to find us
                </a>
              </li>
              <li><i class="bx bx-chevron-right"></i> <a href="https://feeling.choiceqr.com/menu">Our real menu</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="https://responsiblecafes.org/privacy-policy/">Privacy policy</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/includes/navbar.html
<nav id="navbar" class="navbar order-last order-lg-0">
  <ul>
    <li><a class="nav-link scrollto active" href="{% url 'index' %}">Home</a></li>
    <li><a class="nav-link scrollto" href="{% url 'dish:dish-list' dish_type='Breakfasts'%}">Food</a></li>
    <li><a class="nav-link scrollto" href="{% url 'dish:dish-list' dish_type='Coffee'%}">Drinks</a></li>
    <li><a class="nav-link scrollto" href="{% url 'dish:dish-list' dish_type='Cheescakes'%}">Desserts</a></li>
    <li><a class="nav-link scrollto" href="{% url 'dish:dish-list' dish_type='Kids Menu'%}">Kids Menu</a></li>
  </ul>
  <i class="bi bi-list mobile-nav-toggle"></i>
</nav>
{% if user.is_authenticated %}
  <a href="{% url 'user:user-detail' %}" class="nav-link scrollto">Hello, {{ user.username }}!</a>
  <a href="{% url 'logout' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Logout</a>
  <a href="{% url 'order:order-list' %}" class="book-a-table-btn scrollto d-none d-lg-flex">My orders</a>
{% else %}
  <a href="{% url 'login' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Login</a>
{% endif %}

templates/includes/topbar.html
<div id="topbar" class="d-flex align-items-center fixed-top">
  <div class="container d-flex justify-content-center justify-content-md-between">

    <div class="contact-info d-flex align-items-center">
      <i class="bi bi-phone d-flex align-items-center"><span>+380 (99) 468 17 22</span></i>
      <i class="bi bi-clock d-flex align-items-center ms-4"><span> Sat-Thu: 9AM - 21PM, Fri-Sun: 9AM - 22PM</span></i>
    </div>
  </div>
</div>