Cafe_feeling_happy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Cafe_feeling_happy.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("dish/", include("dish.urls", namespace="dish")),
    path("order/", include("order.urls", namespace="order")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dish/urls.py
from django.urls import path

from dish.views import (dish_type_view,
                        add_dish_to_users_order_view,
                        DishDetailView,
                        DishCreateView,
                        DishDeleteView,
                        DishUpdateView)

urlpatterns = [
    path("details/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("details/<int:pk>/add_to_order/", add_dish_to_users_order_view, name="add-to-order"),
    path("create/", DishCreateView.as_view(), name="dish-create"),
    path("<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("<str:dish_type>/", dish_type_view, name="dish-list"),
]

app_name = "dish"

dish/models.py
from django.db import models


class MenuSection(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"


class DishType(models.Model):
    name = models.CharField(max_length=255)
    section = models.ForeignKey(to=MenuSection, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.name}"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    photo = models.CharField(max_length=255, default="")
    type = models.ForeignKey(to=DishType, on_delete=models.DO_NOTHING)
    price = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = "dishes"

    def __str__(self) -> str:
        return f"{self.name}, type({self.type.name}) price:{self.price}"

dish/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from dish.models import Dish, DishType
from order.views import add_dish_to_users_order


def dish_type_view(request: HttpRequest, dish_type: str):
    dish_list = Dish.objects.filter(type__name=dish_type)
    type_obj = DishType.objects.filter(name=dish_type).first()
    section_name = type_obj.section.name
    type_list = DishType.objects.filter(section__name=section_name)

    context = {
        "dish_list": dish_list,
        "type_list": type_list,
        "section_name": section_name
    }

    return render(request, "dish/dish_list.html", context=context)


class DishDetailView(generic.DetailView):
    model = Dish


@login_required
def add_dish_to_users_order_view(request: HttpRequest,
                            pk: int) -> HttpResponseRedirect:
    _, dish_id = add_dish_to_users_order(request, pk)
    return HttpResponseRedirect(reverse_lazy("dish:dish-detail", args=[dish_id]))


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    fields = "__all__"
    template_name = "dish/dish_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dish_types"] = DishType.objects.all()
        return context

    def get_success_url(self):
        dish_type_name = self.object.type.name
        return reverse_lazy("dish:dish-list", args=[dish_type_name])


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish

    def get_success_url(self):
        dish_type_name = self.object.type.name
        return reverse_lazy("dish:dish-list", args=[dish_type_name])


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    fields = "__all__"
    template_name = "dish/dish_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dish_types"] = DishType.objects.all()
        return context

    def get_success_url(self):
        dish_type_name = self.object.id
        return reverse_lazy("dish:dish-detail", args=[dish_type_name])

templates/dish/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <main id="main">
    <section class="inner-page">
      <p><div><br><br><br></div>
      <div class="col-sm-6" style="margin: auto">
        <section id="menu" class="menu section-bg" style="padding: 50px">
          <div class="section-title"><h2>confirm the deletion of the dish</h2></div>
          <div class="row">
            <h4>Are you sure that you want to delete dish {{ dish.name }}?</h4><br>
              <form action="" method="post">
                {% csrf_token %}
                <input type="submit" value="Yes, delete" class="book-a-table-btn scrollto d-none d-lg-flex">
              </form>
              <a href="{% url 'dish:dish-detail' pk=dish.id %}">
                <button class="button" name="food">No</button>
              </a>
          </div>
        </section>
      </div>
    </section>
  </main>
{% endblock %}

templates/dish/dish_detail.html
{% extends "base.html" %}
{% block title %}
<title>{{ dish.name }} Details</title>
{% endblock %}
{% block content %}
<section id="specials" class="specials">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <div>
        <br>
        <br>
            <br>
            <br>
            </div>
          <h2>{{ dish.type.section.name }}</h2>
          <p>{{ dish.name }}</p>
        </div>
        <div class="row" data-aos="fade-up" data-aos-delay="100">
          <div class="col-lg-9 mt-4 mt-lg-0">
            <div class="tab-content">
                <div class="row">
                  <div class="col-lg-8 details order-2 order-lg-1">
                    <h3>Description</h3>
                    <p>{{ dish.description }}</p>
                    <h4>{{ dish.price }} UAH</h4>
                  </div>
                  <div class="col-lg-4 text-center order-1 order-lg-2">
                    <img src={{ dish.photo }} alt={{ dish.name }} class="img-fluid">
                  </div>
                </div>
                <div class="row">
                {% if not user.is_authenticated %}
                  <a href="{% url 'login' %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add to order</a>
                {% else %}
                  <a href="{% url 'dish:add-to-order' pk=dish.id %}" class="book-a-table-btn scrollto d-none d-lg-flex">Add to order</a>
                {% endif %}
                  {% if user.is_superuser %}
                    <a href="{% url 'dish:dish-delete' pk=dish.id %}" class="book-a-table-btn scrollto d-none d-lg-flex">Delete dish</a>
                    <a href="{% url 'dish:dish-update' pk=dish.id %}" class="book-a-table-btn scrollto d-none d-lg-flex">Update dish</a>
                  {% endif %}
                </div>
            </div>
          </div>
        </div>

      </div>
    </section>
{% endblock %}

templates/dish/dish_form.html
{% extends "base.html" %}
{% block title %}
  <title>{{ object|yesno:"Update ,Create" }}{{ dish.name }} dish</title>
  {% endblock %}
{% block content %}
  <main id="main">
    <section class="inner-page">
      <p><div><br><br><br></div>
      <div class="col-sm-6" style="margin: auto">
        <section id="menu" class="menu section-bg" style="padding: 50px">
          <div class="section-title"><h2>{{ object|yesno:"Update ,Create" }}{{ dish.name }} dish</h2></div>
          <div>
            <form action="" method="post">
              {% csrf_token %}
              <input type="text" name="name" class="form-control" placeholder="Name..." value="{{ dish.name }}">
              <textarea name="description" class="form-control" rows="4" required="" id="id_description" placeholder="Description..." >{{ dish.description }}</textarea>
              <input type="text" name="photo" class="form-control" placeholder="URL of image..." value="{{ dish.photo }}">
              <label>Dish type:</label>
              <select name="type" required="" id="id_type" class="form-control">
                {% for type in dish_types %}
                  <option value={{ type.id }} {% if type.id == dish.type.id %}selected{% endif %} >{{ type.name }}</option>
                {% endfor %}
              </select>
              <input type="number" name="price" min="0" required="" id="id_price" class="form-control" placeholder="Price..." value="{{ dish.price }}">
              <input type="submit" value="Submit" class="book-a-table-btn scrollto d-none d-lg-flex" style="margin: auto">
            </form>
          </div>
        </section>
      </div>
    </section>
  </main>
{% endblock %}

templates/dish/dish_list.html
{% extends "base.html" %}
  {% block title %}
  <title>Feeling Happy {{ section_name }}</title>
  {% endblock %}
  {% block content %}
  <main id="main">
    <section class="inner-page">
      <div class="container">
        <p><div><br><br></div>
          <section id="menu" class="menu section-bg">
            <div class="container" data-aos="fade-up">
              {% if user.is_superuser %}
                <a href="{% url 'dish:dish-create' %}" style="float: right; margin-right: 50px;">
                  <button class="button">Add Dish</button>
                </a>
              {% endif %}
              <div class="section-title">
                  <h2>Menu</h2>
                  <p>Our {{ section_name }}</p>
              </div>
              <div class="row" data-aos="fade-up" data-aos-delay="100">
                <div class="col-lg-12 d-flex justify-content-center">
                  <ul id="menu-flters">
                    {% for type in type_list %}
                      <a href="{% url 'dish:dish-list' dish_type=type.name %}">
                        <button type="submit" class="button" name="food" value="type.id">{{ type.name }}
                        </button>
                      </a>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
                {% for dish in dish_list %}
                  <div class="col-lg-6 menu-item filter-starters">
                    <img src={{ dish.photo }} class="menu-img" alt="">
                    <div class="menu-content">
                      <a href="{% url 'dish:dish-detail' pk=dish.id %}">{{ dish.name }}</a><span>{{ dish.price }} UAH</span>
                    </div>
                    <div class="menu-ingredients">
                      {{ dish.description }}
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>
          </section>
        </p>
      </div>
    </section>
  </main>
{%  endblock %}