Cafe_feeling_happy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Cafe_feeling_happy.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("dish/", include("dish.urls", namespace="dish")),
    path("order/", include("order.urls", namespace="order")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dish/urls.py
from django.urls import path

from dish.views import (dish_type_view,
                        add_dish_to_users_order_view,
                        DishDetailView,
                        DishCreateView,
                        DishDeleteView,
                        DishUpdateView)

urlpatterns = [
    path("details/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("details/<int:pk>/add_to_order/", add_dish_to_users_order_view, name="add-to-order"),
    path("create/", DishCreateView.as_view(), name="dish-create"),
    path("<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("<str:dish_type>/", dish_type_view, name="dish-list"),
]

app_name = "dish"

order/urls.py
from django.urls import path

from order.views import (add_dish_to_users_order_view,
                         remove_dish_from_users_order_view,
                         OrderListView,
                         OrderDetailView,
                         OrderConfirmByUserView)

urlpatterns = [
    path("order_list/", OrderListView.as_view(), name="order-list"),
    path("order_detail/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path("order_detail/<int:pk>/add_dish/", add_dish_to_users_order_view, name="order-detail-add"),
    path("<int:pk>/remove_dish/", remove_dish_from_users_order_view, name="order-detail-remove"),
    path("order_detail/<int:pk>/confirm_by_user/", OrderConfirmByUserView.as_view(), name="confirm-order-by-user"),
]

app_name = "order"

order/models.py
from django.db import models
from dish.models import Dish
from user.models import User


class OrderStatus(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "order statuses"

    def __str__(self) -> str:
        return f"{self.name}"


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    status = models.ForeignKey(to=OrderStatus, on_delete=models.DO_NOTHING)
    dishes = models.ManyToManyField(to=Dish, through="OrderDish")
    making_datetime = models.DateTimeField()
    total_amount = models.PositiveIntegerField()
    address = models.CharField(max_length=255, blank=True)

    def __str__(self) -> str:
        return (f"{self.id} Status: {self.status.name} "
                f"creating at: {self.making_datetime}")


class OrderDish(models.Model):
    dish = models.ForeignKey(to=Dish, on_delete=models.DO_NOTHING)
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE)
    dish_count = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = "dishes in order"

    def __str__(self) -> str:
        return f"Order id: {self.order.id}: {self.dish.name} " \
               f"amount: {self.dish_count}"

order/forms.py
from django import forms
from django.core.exceptions import ValidationError

from order.models import Order


class OrderConfirmByUserForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["address"]

order/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from dish.models import Dish
from order.forms import OrderConfirmByUserForm
from order.models import Order, OrderStatus, OrderDish
from user.models import User


def get_or_create_order_credentials(request: HttpRequest, pk: int) -> dict:
    user = User.objects.get(id=request.user.id)
    status = OrderStatus.objects.filter(name="creation").first()
    order = Order.objects.filter(user=user, status=status).first()
    dish = Dish.objects.get(id=pk)
    order_dish = OrderDish.objects.filter(dish=dish, order=order).first()
    return {
        "user": user,
        "status": status,
        "order": order,
        "dish": dish,
        "order_dish": order_dish
    }


def add_dish_to_users_order(request: HttpRequest,
                            pk: int) -> tuple:
    queryset_dict = get_or_create_order_credentials(request, pk)

    if not queryset_dict["order"]:
        queryset_dict["order"] = Order.objects.create(
            user=queryset_dict["user"],
            status=queryset_dict["status"],
            making_datetime=datetime.now(),
            total_amount=0
        )
    if not queryset_dict["order_dish"]:
        queryset_dict["order_dish"] = OrderDish.objects.create(
            dish=queryset_dict["dish"],
            order=queryset_dict["order"],
            dish_count=1
        )
    else:
        queryset_dict["order_dish"].dish_count = queryset_dict[
                                                     "order_dish"
                                                 ].dish_count + 1
        queryset_dict["order_dish"].save()
    queryset_dict["order"].total_amount += queryset_dict["dish"].price
    queryset_dict["order"].save()
    return queryset_dict["order"].id, queryset_dict["dish"].id


class OrderListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = "order/order_list.html"
    context_object_name = "order_list"

    def get_queryset(self) -> QuerySet:
        user = User.objects.get(id=self.request.user.id)
        queryset = Order.objects.filter(user=user).order_by("status")
        return queryset


class OrderDetailView(generic.DetailView):
    model = Order
    template_name = "order/order_detail.html"
    queryset = Order.objects.prefetch_related("dishes")


@login_required
def add_dish_to_users_order_view(request: HttpRequest,
                                 pk: int) -> HttpResponseRedirect:
    order_id, _ = add_dish_to_users_order(request, pk)
    if order_id:
        return HttpResponseRedirect(reverse_lazy("order:order-detail", args=[order_id]))
    else:
        return HttpResponseRedirect(reverse_lazy("order:order-list"))


@login_required
def remove_dish_from_users_order_view(request: HttpRequest,
                                      pk: int) -> HttpResponseRedirect:
    queryset_dict = get_or_create_order_credentials(request, pk)
    queryset_dict["order_dish"].dish_count -= 1
    queryset_dict["order_dish"].save()
    queryset_dict["order"].total_amount -= queryset_dict["dish"].price
    queryset_dict["order"].save()
    if queryset_dict["order_dish"].dish_count == 0:
        queryset_dict["order_dish"].delete()
        if not OrderDish.objects.filter(order=queryset_dict["order"]):
            queryset_dict["order"].delete()
            return HttpResponseRedirect(reverse_lazy("order:order-list"))
    return HttpResponseRedirect(reverse_lazy("order:order-detail", args=[queryset_dict["order"].id]))


class OrderConfirmByUserView(LoginRequiredMixin, generic.UpdateView):
    model = Order
    form_class = OrderConfirmByUserForm
    template_name = 'order/order_detail.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Order, pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('order:order-detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object.status = OrderStatus.objects.filter(name="processing").first()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

templates/order/order_detail.html
{% extends "base.html" %}
{% block title %}
  <title>Order № {{ order.id }}</title>
  {% endblock %}
{% block content %}
  <main id="main">
    <section class="inner-page">
      <p><div><br><br><br></div>
      <div class="col-sm-6" style="margin: auto">
        <section id="menu" class="menu section-bg" style="padding: 50px">
          <div class="section-title"><h2>Order № {{ order.id }}</h2></div>
          <table class="table table-dark" style="background-color: transparent">
            <tr>
              <th>Dish:</th>
              <th style="text-align: center;">Price per dish</th>
              <th style="text-align: center;">Count of dishes</th>
            </tr>
            {% for orderdish in order.orderdish_set.all %}
              <tr>
                <td>{{ orderdish.dish.name }}</td>
                <td style="text-align: center;">{{ orderdish.dish.price }} UAH</td>
                <td style="text-align: center;">{% if not order.address %}<a href="{% url 'order:order-detail-remove' pk=orderdish.dish.id %}">➖</a>{% endif %}   {{ orderdish.dish_count }}   {% if not order.address %}<a href="{% url 'order:order-detail-add' pk=orderdish.dish.id %}">➕</a>{% endif %}</td>
              </tr>
            {% endfor %}
          </table>
          <div class="order-row">
            <p><i>total amount:</i> <b>{{ order.total_amount }}</b> UAH</p>
            <p><i>created at:</i> <b>{{ order.making_datetime.day }}-{{ order.making_datetime.month }}-{{ order.making_datetime.year }}, {{ order.making_datetime.hour }}:{{ order.making_datetime.minute }}</b></p>
            <p><i>status:</i> <b>{{ order.status }}</b></p>
          </div>
          <div>
            {% if not order.address %}
              <form action="{% url 'order:confirm-order-by-user' pk=order.id %}" method="post">
                {% csrf_token %}
                <label for="address">Address for delivery:</label>
                <input type="text" name="address" class="form-control" placeholder="Address...">
                <input type="submit" value="Submit" class="book-a-table-btn scrollto d-none d-lg-flex" style="margin: auto">
              </form>
            {% else %}
              <div class="order-row">
                <p>Your order is in <b>{{ order.status.name }}</b> status. Thank you for order!</p>
              </div>
            {% endif %}
          </div>
        </section>
      </div>
    </section>
  </main>
{% endblock %}

templates/order/order_list.html
{% extends "base.html" %}
{% block title %}
  <title>My orders</title>
  {% endblock %}
{% block content %}
<main id="main">
  <section class="inner-page">
    <div class="container">
      <p><div><br><br></div>
        <section id="menu" class="menu section-bg">
          <div class="container" data-aos="fade-up">
            <div class="section-title"><h2>My orders</h2></div>
            <div class="menu-container" data-aos="fade-up" data-aos-delay="200">
              {% for order in order_list %}
                <div class="col-lg-6 menu-item filter-starters">
                  <h4>Order number: <a href="{% url 'order:order-detail' pk=order.id%}">{{ order.id }}</a></h4>
                  <div class="order-row">
                    <p><i>total amount:</i> <b>{{ order.total_amount }}</b> UAH</p>
                    <p><i>created at:</i> <b>{{ order.making_datetime.day }}-{{ order.making_datetime.month }}-{{ order.making_datetime.year }}, {{ order.making_datetime.hour }}:{{ order.making_datetime.minute }}</b></p>
                    <p><i>status:</i> <b>{{ order.status.name }}</b></p>
                  </div>
                </div>
                {% empty %}
                <h4>There is no orders yet</h4>
              {% endfor %}
            </div>
          </div>
        </section>
      </p>
    </div>
  </section>
</main>
{% endblock %}