Cafe_feeling_happy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from Cafe_feeling_happy.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("dish/", include("dish.urls", namespace="dish")),
    path("order/", include("order.urls", namespace="order")),
    path("user/", include("user.urls", namespace="user")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dish/urls.py
from django.urls import path

from dish.views import (dish_type_view,
                        add_dish_to_users_order_view,
                        DishDetailView,
                        DishCreateView,
                        DishDeleteView,
                        DishUpdateView)

urlpatterns = [
    path("details/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("details/<int:pk>/add_to_order/", add_dish_to_users_order_view, name="add-to-order"),
    path("create/", DishCreateView.as_view(), name="dish-create"),
    path("<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("<str:dish_type>/", dish_type_view, name="dish-list"),
]

app_name = "dish"

user/urls.py
from django.urls import path

from user.views import CreateUserView, UserDetailView, UserUpdateView

urlpatterns = [
    path("registration/", CreateUserView.as_view(), name="registration"),
    path("user_detail/", UserDetailView.as_view(), name="user-detail"),
    path("user_update/<int:pk>", UserUpdateView.as_view(), name="user-update")

]

app_name = "user"

user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from user.models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
        )


class UserUpdateForm(forms.ModelForm):
    MIN_USERNAME_LENGTH = 5
    MAX_USERNAME_LENGTH = 15

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "first_name", "last_name", "email"]

user/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from user.forms import CustomUserCreationForm, UserUpdateForm
from user.models import User


class CreateUserView(generic.CreateView):
    model = User
    form_class = CustomUserCreationForm
    template_name = "user/user_form.html"

    def get_success_url(self) -> str:
        return reverse("login")


class UserDetailView(generic.DetailView):
    model = User
    template_name = "user/user_detail.html"

    def get_object(self, queryset=None):
        return self.request.user


class UserUpdateView(generic.UpdateView):
    model = User
    form_class = UserUpdateForm

    def get_success_url(self) -> str:
        return reverse("user:user-detail")

templates/user/user_detail.html
{% extends "base.html" %}

{% block content %}
<section id="hero" class="d-flex align-items-center">
  <div class="col-sm-6" style="margin: auto">
  <section id="menu" class="menu section-bg">
    <div class="col-sm-6" style="margin: auto">
      <div class="section-title"><h2>User {{ user.username }} info</h2></div>
      <table class="table table-dark" style="background-color: transparent">
        <tr>
          <td>Username:</td>
          <th>{{ user.username }}</th>
        </tr>
        <tr>
          <td>First name:</td>
          <th>{{ user.first_name }}</th>
        </tr>
        <tr>
          <td>Last name:</td>
          <th>{{ user.last_name }}</th>
        </tr>
        <tr>
          <td>E-mail::</td>
          <th>{{ user.email }}</th>
        </tr>
      </table>
      <a href="{% url 'user:user-update' pk=user.id %}">
        <button class="button" name="food" style="margin: auto">Change info</button>
      </a>
    </div>
  </section>
  </div>
</section>
{% endblock %}

templates/user/user_form.html
{% extends "input_form_base.html" %}

{% block title %}
{% if user.is_authenticated %}
  <title>Update {{ user.username }} data</title>
{% else %}
  <title>Registration</title>
{% endif %}
{% endblock %}
{% block page_title %}
{% if user.is_authenticated %}
Update {{ user.username }}'s data
{% else %}
Registration
{% endif %}
{% endblock %}
{% block form %}
  <form method="post" action="" novalidate>
    {% csrf_token %}
    <div class="form-group">
      {% if form.errors.username %}
        {% for message in form.errors.username %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input type="text" name="username" class="form-control" placeholder="Username" value="{{ user.username }}">
    </div>
  {% if not user.is_authenticated %}
    <div class="form-group">
      {% if form.errors.password1 %}
        {% for message in form.errors.password1 %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input id="password-field1" class="form-control" type="password" name="password1" class="form-control" placeholder="Password">
      <span toggle="#password-field1" class="fa fa-fw fa-eye field-icon toggle-password"></span>
    </div>
    <div class="form-group">
      {% if form.errors.password2 %}
        {% for message in form.errors.password2 %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input id="password-field2" type="password" name="password2" class="form-control" placeholder="Confirm password">
      <span toggle="#password-field2" class="fa fa-fw fa-eye field-icon toggle-password"></span>
    </div>
  {% endif %}
    <div class="form-group">
      {% if form.errors.first_name %}
        {% for message in form.errors.first_name %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input type="text" name="first_name" class="form-control" placeholder="First name" value="{{ user.first_name }}">
    </div>
    <div class="form-group">
      {% if form.errors.last_name %}
        {% for message in form.errors.last_name %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input type="text" name="last_name" class="form-control" placeholder="Last name" value="{{ user.last_name }}">
    </div>
    <div class="form-group">
      {% if form.errors.email %}
        {% for message in form.errors.email %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <input type="text" name="email" class="form-control" placeholder="E-mail" value="{{ user.email }}">
    </div>
    <div class="form-group">
      {% if form.errors.first_name %}
        {% for message in form.errors.first_name %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
      <button type="submit" class="btn-book animated fadeInUp" value="Login">
        {% if not user.is_authenticated %}
          Registrate
        {% else %}
          Confirm
        {% endif %}
      </button>
    </div>
  </form>
    <br>
  {% if not user.is_authenticated %}
    <p class="mb-4 text-center">Already have an account?</p>
    <div class="form-group">
      <a href="{% url 'login' %}">
        <button type="submit" class="btn-book animated fadeInUp scrollto">Login</button>
      </a>
    </div>
  {% endif %}
{% endblock %}